### ISSUE TITLE
missing continents for some countries using UNregion

### ISSUE THREAD

**Issue by rlonka** [konstantinstadler/country_converter#23]
I am not sure if this is UNRegion issue or country-converter but running:
`countries = ['AQ', 'GS', 'IO', 'CX']`
`country_converter.convert(names=countries,src='ISO2' , to='UNregion')`
 I get NaN

AQ - Antarctica, GS - SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS, 
CX - COCOS (KEELING) ISLANDS, IO - British Indian Ocean Territory

**Comment by konstantinstadler** [comment]
AQ: No quite sure how I interpret the region for Antarctica at the UN (https://unstats.un.org/unsd/methodology/m49/) - I now put it as own region


CX (these are the Christmas Islands!) - fixed the UNCode and UNregion, fixed the continent to Asia
CC (Cocos Islands) - fixed UNCode and UNregion

GS and also BV (Bouvet Island) - the UN states "South America" as region, but most other sources add it to Antarctica - I added Antarctica as continent, but followed the UN for the region

IO: added UNregion and code, changed continent to Africa

also added some other missing codes and regions
Fixed in version 0.5.3
